# Generated by Django 3.2 on 2021-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_order',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('weight', models.CharField(default='0.00', max_length=6)),
                ('cost', models.CharField(default=0.0, max_length=20)),
                ('id', models.CharField(default='6E5GIC6EG1', max_length=15, primary_key=True, serialize=False)),
                ('ordered_date', models.CharField(default='datetime.now()', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Not Yet Shipped', 'Not Yet Shipped'), ('Order Shipped', 'Order Shipped'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled'), ('Delivery Booked', 'Delivery Booked')], default='Delivery Booked', max_length=50)),
                ('location', models.TextField(default='Not Yet Shipped')),
                ('shipment_date', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
