# Generated by Django 3.2 on 2021-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order',
            name='id',
            field=models.CharField(default='GA59CGBCHC', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new_order',
            name='ordered_date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
