# Generated by Django 3.2 on 2021-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210419_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order',
            name='id',
            field=models.CharField(default='2H984FAF73', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new_order',
            name='ordered_date',
            field=models.DateTimeField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='new_order',
            name='shipment_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
