# Generated by Django 3.2.2 on 2021-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210419_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='new_order',
            name='id',
            field=models.CharField(default='BBA1D5681D', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new_order',
            name='ordered_date',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
